#!/usr/bin/env bash
# This Installs, configures, and starts the server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html

SERVER_CONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
	add_header X-Served-By \"$(hostname)\";
        location / {
                try_files \$uri \$uri/ =404;
        }
        error_page 404 /error-page.html;
        location = /error-page.html {
                internal;
        }
        if (\$request_filename ~ redirect_me){
                rewrite ^ https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;
        }
}"

echo "Ceci n'est pas une page" > /var/www/html/error-page.html
echo "$SERVER_CONFIG" > /etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
        service nginx start
else
        service nginx restart
fi
