#!/usr/bin/env bash
# This Fixes a container's nginx and makes sure it is running on port 80

sudo apt-get update
sudo apt-get -y install nginx
if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
